### ISSUE TITLE
Support for DetectNet in TensorRT

### ISSUE THREAD

**Issue by GEngels** [NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference#13]
Thanks a lot for the great Isaac project! 

I am interested in using DetectNet with TensorRT optimization, but native model support is only provided for dope & Unet. On the isaac_ros_object_detection repo it explicitly says that there is no support for tensorrt and DetectNet. 

My question is if this will be support in the future or if I will have to implement this myself?

**Comment by gordongrigor** [comment]
Triton uses TensorRT for inference, hence TensorRT is used in the object detection package.

There is a bug which was not resolved at the time of release, which is why the release supported Triton and not TensorRT for the object detection package.  We will address this bug in a future release.
