### ISSUE TITLE
colcon build error: libcudnn.so.8, not found (try using -rpath or -rpath-link)

### ISSUE THREAD

**Issue by Aki1608** [NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference#17]
I am trying to run this on AGX Xavier in docker container. After cloning three repo: isaac_ros_image_segmentation, isaac_ros_common, and Isaac_ros_dnn_inference, when I run colcon build, I get the following error.

`/usr/bin/ld: warning: libcudnn.so.8, needed by /usr/lib/libopencv_dnn.so.4.5.0, not found (try using -rpath or -rpath-link)
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnDestroy@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnDestroyPoolingDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnCreateTensorDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnSetActivationDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnDestroyConvolutionDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnGetConvolutionForwardAlgorithmMaxCount@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnGetConvolutionForwardAlgorithm_v7@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnDestroyTensorDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnDestroyTensorTransformDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnCreateActivationDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnSetConvolution2dDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnSetConvolutionGroupCount@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnConvolutionBackwardData@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnSetTensorNdDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnSetConvolutionMathType@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnGetTensorSizeInBytes@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnGetConvolutionBackwardDataAlgorithmMaxCount@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnSoftmaxForward@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnCreate@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnGetErrorString@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnDestroyActivationDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnDestroyFilterDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnSetStream@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnPoolingForward@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnDivisiveNormalizationForward@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnGetCudartVersion@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnGetVersion@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnSetFilter4dDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnSetPooling2dDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnSetLRNDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnDestroyLRNDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnTransformTensorEx@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnSetConvolutionNdDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnSetPoolingNdDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnConvolutionBiasActivationForward@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnLRNCrossChannelForward@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnSetFilterNdDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnCreateFilterDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnCreateTensorTransformDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnGetConvolutionNdForwardOutputDim@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnGetTensorNdDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnSetTensor4dDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnConvolutionForward@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnCreateLRNDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnGetConvolutionBackwardDataAlgorithm_v7@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnSetTensorTransformDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnCreatePoolingDescriptor@libcudnn.so.8'
/usr/lib/libopencv_dnn.so.4.5.0: undefined reference to "cudnnCreateConvolutionDescriptor@libcudnn.so.8'
collect2: error: ld returned 1 exit status
make[2]: *** [dnn_image_encoder] Error 1
make[1]: *** [CMakeFiles/dnn_image_encoder.dir/all] Error 2
make: *** [all] Error 2
`

I also tried `git lfs pull`. But that didn't work. I tried exporting the path of `libcudnn.so.8` into the library path, but that is not working as well. What can be the problem here?

**Comment by Aki1608** [comment]
Also I am using the` release-ea2.1` branch.

**Comment by Aki1608** [comment]
while running sudo ldconfig inside docker container, this files shows empty.
`admin@agx:/usr/lib/aarch64-linux-gnu$ sudo ldconfig
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libnvparsers.so.8 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libnvinfer.so.8 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libnvonnxparser.so.8 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libnvinfer.so is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libnvinfer_plugin.so.8 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libcudnn_adv_train.so is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libcudnn_adv_infer.so is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libcudnn_ops_infer.so is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libcudnn_ops_train.so is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libcudnn.so is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libnvinfer_plugin.so is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libcudnn_ops_infer.so.8 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer.so is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer.so.8 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libcudnn_cnn_train.so.8 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libcudnn_adv_train.so.8 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libcudnn_ops_train.so.8 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libcudnn.so.8 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libcudnn_adv_infer.so.8 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libnvonnxparser.so is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libnvparsers.so is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libcudnn.so.8.2.1 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer.so.8.2.1 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libcudnn_cnn_train.so.8.2.1 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libcudnn_adv_infer.so.8.2.1 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libcudnn_ops_train.so.8.2.1 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libnvinfer.so.8.2.1 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libnvinfer_builder_resource.so.8.2.1 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libnvparsers.so.8.2.1 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libcudnn_adv_train.so.8.2.1 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libnvonnxparser.so.8.2.1 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libcudnn_ops_infer.so.8.2.1 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/libnvinfer_plugin.so.8.2.1 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/aarch64-linux-gnu/tegra/libcudnn.so.8 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/libvisionworks_tracking.so.0.88 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/libvisionworks_sfm.so is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/libvisionworks.so is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/libvisionworks_sfm.so.0.90 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/libvisionworks_tracking.so is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/libvisionworks_tracking.so.0.88.2 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/libvisionworks.so.1.6.0 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/libvisionworks_sfm.so.0.90.4 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/libvisionworks.so.1.6 is empty, not checked.
`

This files are present in Host devices. 


![Screenshot from 2022-07-14 17-12-59](https://user-images.githubusercontent.com/52529996/178974884-ce3c850e-c318-4508-ab89-0f9ce2cf2d18.png)

It looks like inside docker they are not properly mounting.

**Comment by hemalshahNV** [comment]
Have you updated your default runtime in `/etc/docker/daemon.json` to "nvidia"? That setting informs Docker daemon to mount a set of files from your host into the container.

**Comment by Aki1608** [comment]
Hi @hemalshahNV, sorry for late reply. Yes, we did that as well.

**Comment by hemalshahNV** [comment]
We're not able to reproduce the issue on our JP4.6 devices yet so our theory is that there is something different about your host. Could you try running `nvidia-container-cli --v` on the host to get which version of the NVIDIA Container runtime you are running? Also, could you post the LD_LIBRARY_PATH from inside the container too?
