### ISSUE TITLE
isaac_ros_nitros header file dependency

### ISSUE THREAD

**Issue by arainbilal** [NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference#22]
Hi,

Request to verify if required to add explicitly the following in isaac_ros_dnn_encoders/[CMakeLists.txt](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference/blob/main/isaac_ros_dnn_encoders/CMakeLists.txt):

```
find_package(isaac_ros_nitros REQUIRED)
```
The header file is required by `dnn_image_encoder_node.hpp`
https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference/blob/c14014cbf5694df8195ccdf3e52d2da6cf31020e/isaac_ros_dnn_encoders/include/isaac_ros_dnn_encoders/dnn_image_encoder_node.hpp#L24 

I was not able to get compile without adding find_package. Thanks in advance for your help.

**Comment by hemalshahNV** [comment]
Thanks for pointing this out. We tested clean checkouts as the following but were unable to reproduce any issues. Did we miss anything? 

```bash
mkdir tmp_ros_ws
cd tmp_ros_ws
mkdir src
cd src
git clone https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference.git
git clone https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nitros.git
git clone https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common.git
cd ..
colcon build --packages-up-to isaac_ros_dnn_encoders
```

The `find_package` line should not be required because that engages cmake machinery to find `isaac_ros_nitros` while `package.xml` should already report `isaac_ros_nitros` package as a dependency to ament which gets picked up with the following:
```
find_package(ament_cmake_auto REQUIRED)
ament_auto_find_build_dependencies()
```

**Comment by arainbilal** [comment]
Hi @hemalshahNV, thank you for your response. I agree with you; it is not a problem and I have verified as follows:

1. Clone repositories in the workspace folder
```
cd isaac_ros-dev && mkdir -p tmp_ros_ws/src && cd tmp_ros_ws/src
git clone https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference.git
git clone https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nitros.git
git clone https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common.git
```

2. Compilation

```
cd isaac_ros_common/scripts
./run_dev.sh
cd 
colcon build --packages-up-to isaac_ros_dnn_encoders
```
I can verify that everything compiles. I have a quick question about the dependency on`isaac_ros_tensor_list_interfaces` in `isaac_ros_common`. In fact, I need to clone the `isaac_ros_common` just for this dependency. May be an idea to consider moving the `interfaces` into a separate repository (may be called `isaac_ros_interfaces`) to include those and may be keep the common for the docker files and the scripts. Just a thought. 
Thank you again for your help.
