### ISSUE TITLE
dnn_encoder GXF_OUT_OF_MEMORY 

### ISSUE THREAD

**Issue by philnguyenresson** [NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference#29]
Hi, I get a memory error if I just try running the dnn_encoder node by itself.
Here is the error:
`[component_container_mt-1] [INFO] [1678771154.245686357] [dnn_image_encoder]: [NitrosNode] Linking Nitros pub/sub to the loaded application
[component_container_mt-1] [INFO] [1678771154.245800463] [dnn_image_encoder]: [NitrosNode] Calling user's post-load-graph callback
[component_container_mt-1] [INFO] [1678771154.245811388] [dnn_image_encoder]: In DNN Image Encoder Node postLoadGraphCallback().
[component_container_mt-1] [INFO] [1678771154.245908426] [dnn_image_encoder]: [NitrosContext] Initializing applicaiton...
[component_container_mt-1] 2023-03-14 05:19:14.360 ERROR gxf/std/entity_warden.cpp@379: Failed to initialize component 00050 (allocator)
[component_container_mt-1] 2023-03-14 05:19:14.360 ERROR gxf/core/runtime.cpp@551: Could not initialize entity 'NQAKHWCELM_reshaper' (E45): GXF_OUT_OF_MEMORY
[component_container_mt-1] 2023-03-14 05:19:14.360 ERROR gxf/std/program.cpp@191: Failed to activate entity 00045 named NQAKHWCELM_reshaper: GXF_OUT_OF_MEMORY
[component_container_mt-1] 2023-03-14 05:19:14.360 ERROR gxf/std/program.cpp@193: Deactivating...
[component_container_mt-1] 2023-03-14 05:19:14.378 ERROR gxf/core/runtime.cpp@1158: Graph activation failed with error: GXF_OUT_OF_MEMORY
[component_container_mt-1] [ERROR] [1678771154.378456398] [dnn_image_encoder]: [NitrosContext] GxfGraphActivate Error: GXF_OUT_OF_MEMORY
[component_container_mt-1] [ERROR] [1678771154.378511054] [dnn_image_encoder]: [NitrosNode] runGraphAsync Error: GXF_OUT_OF_MEMORY
[component_container_mt-1] terminate called after throwing an instance of 'std::runtime_error'
[component_container_mt-1]   what():  [NitrosNode] runGraphAsync Error: GXF_OUT_OF_MEMORY
[ERROR] [component_container_mt-1]: process has died [pid 11030, exit code -6, cmd '/opt/ros/humble/install/lib/rclcpp_components/component_container_mt --ros-args -r __node:=tensor_rt_container -r __ns:=/isaac_ros_tensor_rt'].
`

Here is the relevant code, im just launching the dnn encoder node (though with large size, but im not sure why its causing a memory error)

`    # The Image to Tensor encoder
    encoder_node = ComposableNode(
        name="dnn_image_encoder",
        package="isaac_ros_dnn_encoders",
        plugin="nvidia::isaac_ros::dnn_inference::DnnImageEncoderNode",
        parameters=[
            {
                "network_image_width": 2432,
                "network_image_height": 2048,
            }
        ],
        remappings=[("encoded_tensor", "tensor_pub")],
    )
`

This is with the isaac_ros_dev-x86_64 image, using isaac_ros_common/scripts/run_dev.sh

**Comment by jaiveersinghNV** [comment]
Based on the error, it looks like your machine is running out of memory (note the `GXF_OUT_OF_MEMORY` error in the log snippet).

What is the input image encoding? Are you running this on an x86_64 system with a discrete GPU? If so, what model of GPU? 

It seems like this input image size is simply too big to encode in a performant way.

**Comment by philnguyenresson** [comment]
I'm running on a GTX1070 GPU, and I've also run into the error on a Jetson Xavier NX.
The image  is BGR8

**Comment by jaiveersinghNV** [comment]
To ensure the best performance, the Isaac ROS suite of packages preallocates memory blocks based on the desired image size. Unfortunately, the GTX 1070 GPU and Jetson Xavier NX both have 8 GB of memory, which is not sufficient for the 2432x2048 image size that you have configured.

Could you try reducing the image size used for this DNN encoder? What network are you trying to use?

**Comment by philnguyenresson** [comment]
reducing the image size does work, with the limit being around 1900x2000 for 8GB.
The memory issues occur when running the encoder alone, but the model I am using is the ssd_mobilenet from here:[https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md )

**Comment by ammar-n-abbas** [comment]
Hi, We are facing the same issue. We are using Nvidia RTX A2000 12GB graphics card. When we monitor the the GPU usage while launching through realsense or rosbag example for foundation pose, the memory usage does not go above 6.5 GB and we get the following error (also pasting all the warnings): 
```[component_container_mt-1] 2024-08-22 11:39:42.353 WARN  gxf/std/program.cpp@532: No GXF scheduler specified.
.
[component_container_mt-1] 2024-08-22 11:39:43.643 WARN  gxf/std/yaml_file_loader.cpp@1077: Using unregistered parameter 'dev_id' in component 'stream'.
.
[component_container_mt-1] 2024-08-22 11:39:46.508 WARN  gxf/std/yaml_file_loader.cpp@1077: Using unregistered parameter 'dummy_rx' in component ''.
[component_container_mt-1] 2024-08-22 11:39:46.509 WARN  gxf/std/yaml_file_loader.cpp@1077: Using unregistered parameter 'dummy_rx' in component ''.
[component_container_mt-1] 2024-08-22 11:39:46.509 WARN  gxf/std/yaml_file_loader.cpp@1077: Using unregistered parameter 'dev_id' in component 'stream'.
.
[component_container_mt-1] 2024-08-22 11:39:46.514 WARN  gxf/std/scheduling_terms.cpp@333: 'min_size' parameter in MultiMessageAvailableSchedulingTerm is deprecated. Use 'min_sum' with SumOfAll sampling mode instead
[component_container_mt-1] 2024-08-22 11:39:46.514 WARN  gxf/std/scheduling_terms.cpp@333: 'min_size' parameter in MultiMessageAvailableSchedulingTerm is deprecated. Use 'min_sum' with SumOfAll sampling mode instead
[component_container_mt-1] 2024-08-22 11:39:46.514 WARN  gxf/std/scheduling_terms.cpp@333: 'min_size' parameter in MultiMessageAvailableSchedulingTerm is deprecated. Use 'min_sum' with SumOfAll sampling mode instead
[component_container_mt-1] 2024-08-22 11:39:46.514 WARN  gxf/std/scheduling_terms.cpp@333: 'min_size' parameter in MultiMessageAvailableSchedulingTerm is deprecated. Use 'min_sum' with SumOfAll sampling mode instead
[component_container_mt-1] 2024-08-22 11:39:46.514 WARN  gxf/std/scheduling_terms.cpp@333: 'min_size' parameter in MultiMessageAvailableSchedulingTerm is deprecated. Use 'min_sum' with SumOfAll sampling mode instead
.
[component_container_mt-1] [INFO] [1724323186.518284133] [foundationpose_node]: [NitrosNode] Node was started
[component_container_mt-1] Could not open file 
[component_container_mt-1] Could not open file 
[component_container_mt-1] [ERROR] [1724323187.887672387] [TRT]: TRT ERROR: ModelImporter.cpp:733: Failed to parse ONNX model from file: 
[component_container_mt-1] [ERROR] [1724323188.011007469] [tensor_rt]: Unable to read tensor shape info from TRT Model Engine or from ONNX file.
[component_container_mt-1] [WARN] [1724323188.011051778] [tensor_rt]: Failed to get block size from model, set to the default size: 67108864.
[component_container_mt-1] [INFO] [1724323188.011117585] [tensor_rt]: Tensors 67108864 bytes, num outputs 40 x tensors per output 3 = 120 blocks
[component_container_mt-1] [INFO] [1724323188.011197329] [tensor_rt]: [NitrosNode] Initializing and running GXF graph
[component_container_mt-1] 2024-08-22 11:39:48.015 ERROR gxf/std/block_memory_pool.cpp@77: Failure in cudaMalloc. cuda_error: cudaErrorMemoryAllocation, error_str: out of memory
[component_container_mt-1] 2024-08-22 11:39:48.015 ERROR gxf/std/entity_warden.cpp@437: Failed to initialize component 00157 (pool)
[component_container_mt-1] 2024-08-22 11:39:48.015 ERROR gxf/core/runtime.cpp@702: Could not initialize entity 'XMIYROHBPH_inference' (E152): GXF_OUT_OF_MEMORY
[component_container_mt-1] 2024-08-22 11:39:48.015 ERROR gxf/std/program.cpp@283: Failed to activate entity 00152 named XMIYROHBPH_inference: GXF_OUT_OF_MEMORY
[component_container_mt-1] 2024-08-22 11:39:48.015 ERROR gxf/std/program.cpp@285: Deactivating...
[component_container_mt-1] 2024-08-22 11:39:48.015 ERROR gxf/core/runtime.cpp@1452: Graph activation failed with error: GXF_OUT_OF_MEMORY
[component_container_mt-1] [ERROR] [1724323188.015653036] [tensor_rt]: [NitrosContext] GxfGraphActivate Error: GXF_OUT_OF_MEMORY
[component_container_mt-1] [ERROR] [1724323188.015668492] [tensor_rt]: [NitrosNode] runGraphAsync Error: GXF_OUT_OF_MEMORY
[component_container_mt-1] terminate called after throwing an instance of 'std::runtime_error'
[component_container_mt-1]   what():  [NitrosNode] runGraphAsync Error: GXF_OUT_OF_MEMORY
[ERROR] [component_container_mt-1]: process has died [pid 922, exit code -6, cmd '/opt/ros/humble/lib/rclcpp_components/component_container_mt --ros-args -r __node:=container -r __ns:=/isaac_ros_examples'].```
