### ISSUE TITLE
colcon build --symlink-install error

### ISSUE THREAD

**Issue by kong9999** [NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference#33]
**Hello. I am now faced with the following problems**
![image](https://user-images.githubusercontent.com/51771035/236808621-50da898f-5128-4b13-a476-2a4c95fd774c.png)
admin@ubuntu:/workspaces/isaac_ros-dev$ colcon build --symlink-install
Starting >>> isaac_ros_common
Starting >>> isaac_ros_test
Finished <<< isaac_ros_common [0.34s]                                                          
Starting >>> isaac_ros_gxf
Starting >>> isaac_ros_nitros_interfaces
Starting >>> isaac_ros_tensor_list_interfaces
Starting >>> isaac_ros_apriltag_interfaces
Starting >>> isaac_ros_pointcloud_interfaces
Starting >>> isaac_ros_bi3d_interfaces
Finished <<< isaac_ros_gxf [0.25s]                                                                                                    
Finished <<< isaac_ros_nitros_interfaces [0.57s]                                                              
Finished <<< isaac_ros_test [0.91s]
Starting >>> isaac_ros_nitros
Finished <<< isaac_ros_pointcloud_interfaces [0.57s]
Finished <<< isaac_ros_bi3d_interfaces [0.58s]
Finished <<< isaac_ros_apriltag_interfaces [0.62s]
Finished <<< isaac_ros_tensor_list_interfaces [0.66s]                                                                   
Starting >>> isaac_ros_dnn_inference_test
Finished <<< isaac_ros_nitros [0.28s]                                                                                
Starting >>> isaac_ros_nitros_camera_info_type
Starting >>> isaac_ros_nitros_image_type
Starting >>> isaac_ros_nitros_tensor_list_type
Starting >>> isaac_ros_nitros_disparity_image_type
Starting >>> isaac_ros_nitros_point_cloud_type
Starting >>> isaac_ros_nitros_april_tag_detection_array_type
Starting >>> isaac_ros_nitros_compressed_image_type
Starting >>> isaac_ros_nitros_detection2_d_array_type
Starting >>> isaac_ros_nitros_flat_scan_type
Starting >>> isaac_ros_nitros_imu_type
Starting >>> isaac_ros_nitros_occupancy_grid_type
Starting >>> isaac_ros_nitros_pose_array_type                                                                                   
Starting >>> isaac_ros_nitros_pose_cov_stamped_type
Starting >>> isaac_ros_nitros_std_msg_type
Finished <<< isaac_ros_dnn_inference_test [0.33s]
Finished <<< isaac_ros_nitros_image_type [0.52s]                                             
Finished <<< isaac_ros_nitros_tensor_list_type [0.52s]
Starting >>> isaac_ros_tensor_rt
Starting >>> isaac_ros_triton
Finished <<< isaac_ros_nitros_point_cloud_type [0.54s]
Finished <<< isaac_ros_nitros_compressed_image_type [0.53s]
Finished <<< isaac_ros_nitros_camera_info_type [0.60s]
Finished <<< isaac_ros_nitros_disparity_image_type [0.58s]                                     
Starting >>> isaac_ros_image_proc
Starting >>> isaac_ros_stereo_image_proc
Finished <<< isaac_ros_nitros_occupancy_grid_type [0.59s]
Finished <<< isaac_ros_nitros_flat_scan_type [0.63s]
Finished <<< isaac_ros_nitros_april_tag_detection_array_type [0.66s]                                     
Finished <<< isaac_ros_nitros_imu_type [0.64s]
Finished <<< isaac_ros_nitros_detection2_d_array_type [0.67s]
Finished <<< isaac_ros_nitros_std_msg_type [0.65s]
Finished <<< isaac_ros_nitros_pose_cov_stamped_type [0.68s]
Finished <<< isaac_ros_nitros_pose_array_type [0.70s]
Finished <<< isaac_ros_tensor_rt [0.39s]                                                                       
Finished <<< isaac_ros_stereo_image_proc [0.33s]
Finished <<< isaac_ros_image_proc [0.37s]
Starting >>> isaac_ros_dnn_encoders
Starting >>> isaac_ros_image_pipeline
Finished <<< isaac_ros_image_pipeline [0.16s]                                                                  
Finished <<< isaac_ros_dnn_encoders [0.18s]
[Processing: isaac_ros_triton]                           
[Processing: isaac_ros_triton]                                   
[Processing: isaac_ros_triton]                                     
[Processing: isaac_ros_triton]                                     
[Processing: isaac_ros_triton]                                     
[Processing: isaac_ros_triton]                                     
[Processing: isaac_ros_triton]                                     
[Processing: isaac_ros_triton]                                     
[Processing: isaac_ros_triton]                                     
[Processing: isaac_ros_triton]                                     
[Processing: isaac_ros_triton]                                     
[Processing: isaac_ros_triton]                                     
[Processing: isaac_ros_triton]                                     
[Processing: isaac_ros_triton]                                     
[Processing: isaac_ros_triton]                                     
[Processing: isaac_ros_triton]                                     
[Processing: isaac_ros_triton]                                     
[Processing: isaac_ros_triton]                                     
[Processing: isaac_ros_triton]                                     
[Processing: isaac_ros_triton]                                     
[Processing: isaac_ros_triton]                                       
[Processing: isaac_ros_triton]                                       
[Processing: isaac_ros_triton]                                       
[Processing: isaac_ros_triton]                                           
--- stderr: isaac_ros_triton                                              
CMake Warning (dev) at /workspaces/isaac_ros-dev/build/isaac_ros_triton/_deps/protobuf-src/cmake/install.cmake:60 (message):
  The file
  "/workspaces/isaac_ros-dev/build/isaac_ros_triton/_deps/protobuf-src/src/google/protobuf/stubs/io_win32.h"
  is listed in
  "/workspaces/isaac_ros-dev/build/isaac_ros_triton/_deps/protobuf-src/cmake/cmake/extract_includes.bat.in"
  but there not exists.  The file will not be installed.
Call Stack (most recent call first):
  /workspaces/isaac_ros-dev/build/isaac_ros_triton/_deps/protobuf-src/cmake/CMakeLists.txt:231 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

---
Finished <<< isaac_ros_triton [12min 21s]

Summary: 30 packages finished [12min 23s]
  1 package had stderr output: isaac_ros_triton

**I compiled it again and it passed, but ran an error**
admin@ubuntu:/workspaces/isaac_ros-dev$ ros2 launch isaac_ros_triton isaac_ros_triton.launch.py model_name:=peoplesemsegnet_shuffleseg model_repository_paths:=['/tmp/models'] input_binding_names:=['input_2:0'] output_binding_names:=['argmax_1']
[INFO] [launch]: All log files can be found below /home/admin/.ros/log/2023-05-08-19-27-24-197165-ubuntu-38276
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [component_container-1]: process started with pid [38287]
[component_container-1] [INFO] [1683545244.506770490] [triton.triton_container]: Load Library: /workspaces/isaac_ros-dev/install/isaac_ros_triton/lib/libtriton_node.so
[component_container-1] [INFO] [1683545244.515595606] [triton.triton_container]: Found class: rclcpp_components::NodeFactoryTemplate<nvidia::isaac_ros::dnn_inference::TritonNode>
[component_container-1] [INFO] [1683545244.515607822] [triton.triton_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<nvidia::isaac_ros::dnn_inference::TritonNode>
[component_container-1] [INFO] [1683545244.516896817] [NitrosContext]: [NitrosContext] Creating a new shared context
[component_container-1] [INFO] [1683545244.516939368] [triton]: [NitrosNode] Initializing NitrosNode
[component_container-1] [INFO] [1683545244.517151223] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/std/libgxf_std.so
[component_container-1] [INFO] [1683545244.518583265] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_gxf_helpers.so
[component_container-1] [INFO] [1683545244.519689770] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_sight.so
[component_container-1] [INFO] [1683545244.520837142] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_atlas.so
[component_container-1] [INFO] [1683545244.522522658] [NitrosContext]: [NitrosContext] Loading application: '/workspaces/isaac_ros-dev/install/isaac_ros_nitros/share/isaac_ros_nitros/config/type_adapter_nitros_context_graph.yaml'
[component_container-1] [INFO] [1683545244.522826900] [NitrosContext]: [NitrosContext] Initializing application...
[component_container-1] [INFO] [1683545244.523598733] [NitrosContext]: [NitrosContext] Running application...
[component_container-1] 2023-05-08 19:27:24.523 WARN  gxf/std/program.cpp@456: No system specified. Nothing to do
[component_container-1] [INFO] [1683545244.523811451] [triton]: [NitrosNode] Starting NitrosNode
[component_container-1] [INFO] [1683545244.523818955] [triton]: [NitrosNode] Loading built-in preset extension specs
[component_container-1] [INFO] [1683545244.524726445] [triton]: [NitrosNode] Loading built-in extension specs
[component_container-1] [INFO] [1683545244.524732624] [triton]: [NitrosNode] Loading preset extension specs
[component_container-1] [INFO] [1683545244.525567989] [triton]: [NitrosNode] Loading extension specs
[component_container-1] [INFO] [1683545244.525573983] [triton]: [NitrosNode] Loading generator rules
[component_container-1] [INFO] [1683545244.525682813] [triton]: [NitrosNode] Loading extensions
[component_container-1] [INFO] [1683545244.525782215] [triton]: [NitrosContext] Loading extension: gxf/lib/cuda/libgxf_cuda.so
[component_container-1] [INFO] [1683545244.526770314] [triton]: [NitrosContext] Loading extension: gxf/lib/serialization/libgxf_serialization.so
[component_container-1] [INFO] [1683545244.528213645] [triton]: [NitrosContext] Loading extension: gxf/triton/libgxf_triton_ext.so
[component_container-1] [INFO] [1683545244.566561048] [triton]: [NitrosNode] Loading graph to the optimizer
[component_container-1] [INFO] [1683545244.568408689] [triton]: [NitrosNode] Running optimization
[component_container-1] [INFO] [1683545244.624025549] [triton]: [NitrosNode] Obtaining graph IO group info from the optimizer
[component_container-1] [INFO] [1683545244.628675965] [triton]: [NitrosNode] Creating negotiated publishers/subscribers
[component_container-1] [INFO] [1683545244.628837947] [triton]: [NitrosPublisherSubscriberGroup] Pinning the component "triton_request/input" (type="nvidia::gxf::DoubleBufferReceiver") to use its compatible format only: "nitros_tensor_list_nchw_rgb_f32"
[component_container-1] [INFO] [1683545244.630889230] [triton]: [NitrosPublisherSubscriberGroup] Pinning the component "vault/vault" (type="nvidia::gxf::Vault") to use its compatible format only: "nitros_tensor_list_nhwc_rgb_f32"
[component_container-1] [INFO] [1683545244.631115386] [triton]: [NitrosNode] Starting negotiation...
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/triton' in container '/triton/triton_container'
[component_container-1] [INFO] [1683545245.631405477] [triton]: [NitrosNode] Starting post negotiation setup
[component_container-1] [INFO] [1683545245.631538294] [triton]: [NitrosNode] Getting data format negotiation results
[component_container-1] [INFO] [1683545245.631565391] [triton]: [NitrosSubscriber] Negotiation ended with no results
[component_container-1] [INFO] [1683545245.631581754] [triton]: [NitrosSubscriber] Use the compatible subscriber: topic_name="/tensor_pub", data_format="nitros_tensor_list_nchw_rgb_f32"
[component_container-1] [INFO] [1683545245.631688876] [triton]: [NitrosPublisher] Negotiation ended with no results
[component_container-1] [INFO] [1683545245.631705792] [triton]: [NitrosPublisher] Use only the compatible publisher: topic_name="/tensor_sub", data_format="nitros_tensor_list_nhwc_rgb_f32"
[component_container-1] [INFO] [1683545245.631729856] [triton]: [NitrosNode] Exporting the final graph based on the negotiation results
[component_container-1] [INFO] [1683545245.655225949] [triton]: [NitrosNode] Wrote the final top level YAML graph to "/workspaces/isaac_ros-dev/install/isaac_ros_triton/share/isaac_ros_triton/SSPKHGPSGC.yaml"
[component_container-1] [INFO] [1683545245.655273208] [triton]: [NitrosNode] Calling user's pre-load-graph callback
[component_container-1] [INFO] [1683545245.655277548] [triton]: [NitrosNode] Loading application
[component_container-1] [INFO] [1683545245.655282462] [triton]: [NitrosContext] Loading application: '/workspaces/isaac_ros-dev/install/isaac_ros_triton/share/isaac_ros_triton/SSPKHGPSGC.yaml'
[component_container-1] 2023-05-08 19:27:25.656 WARN  gxf/std/yaml_file_loader.cpp@952: Using unregistered parameter 'dummy_rx' in component 'requester'.
[component_container-1] [INFO] [1683545245.656199292] [triton]: [NitrosNode] Linking Nitros pub/sub to the loaded application
[component_container-1] [INFO] [1683545245.656242672] [triton]: [NitrosNode] Calling user's post-load-graph callback
[component_container-1] [INFO] [1683545245.656248151] [triton]: In TritonNode postLoadGraphCallback().
[component_container-1] [INFO] [1683545245.656274709] [triton]: [NitrosContext] Initializing application...
[component_container-1] WARNING: infer_trtis_server.cpp:1219 NvDsTritonServerInit suggest to set model_control_mode:none. otherwise may cause unknow issues.
[component_container-1] I0508 11:27:25.745748 38287 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7fad20000000' with size 268435456
[component_container-1] I0508 11:27:25.745860 38287 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
[component_container-1] I0508 11:27:25.746443 38287 server.cc:563] 
[component_container-1] +------------------+------+
[component_container-1] | Repository Agent | Path |
[component_container-1] +------------------+------+
[component_container-1] +------------------+------+
[component_container-1] 
[component_container-1] I0508 11:27:25.746452 38287 server.cc:590] 
[component_container-1] +---------+------+--------+
[component_container-1] | Backend | Path | Config |
[component_container-1] +---------+------+--------+
[component_container-1] +---------+------+--------+
[component_container-1] 
[component_container-1] I0508 11:27:25.746456 38287 server.cc:633] 
[component_container-1] +-------+---------+--------+
[component_container-1] | Model | Version | Status |
[component_container-1] +-------+---------+--------+
[component_container-1] +-------+---------+--------+
[component_container-1] 
[component_container-1] I0508 11:27:25.767131 38287 metrics.cc:864] Collecting metrics for GPU 0: NVIDIA GeForce RTX 3080
[component_container-1] I0508 11:27:25.767250 38287 metrics.cc:757] Collecting CPU metrics
[component_container-1] I0508 11:27:25.767315 38287 tritonserver.cc:2264] 
[component_container-1] +----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
[component_container-1] | Option                           | Value                                                                                                                                                                                                |
[component_container-1] +----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
[component_container-1] | server_id                        | triton                                                                                                                                                                                               |
[component_container-1] | server_version                   | 2.26.0                                                                                                                                                                                               |
[component_container-1] | server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics trace logging |
[component_container-1] | model_repository_path[0]         | /tmp/models                                                                                                                                                                                          |
[component_container-1] | model_control_mode               | MODE_EXPLICIT                                                                                                                                                                                        |
[component_container-1] | strict_model_config              | 1                                                                                                                                                                                                    |
[component_container-1] | rate_limit                       | OFF                                                                                                                                                                                                  |
[component_container-1] | pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                                            |
[component_container-1] | cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                                                                             |
[component_container-1] | response_cache_byte_size         | 0                                                                                                                                                                                                    |
[component_container-1] | min_supported_compute_capability | 6.0                                                                                                                                                                                                  |
[component_container-1] | strict_readiness                 | 1                                                                                                                                                                                                    |
[component_container-1] | exit_timeout                     | 30                                                                                                                                                                                                   |
[component_container-1] +----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
[component_container-1] 
[component_container-1] [INFO] [1683545245.767601971] [triton]: [NitrosContext] Running application...
[component_container-1] I0508 11:27:25.768601 38287 model_lifecycle.cc:459] loading: peoplesemsegnet_shuffleseg:1
[component_container-1] I0508 11:27:25.790066 38287 tensorrt.cc:5442] TRITONBACKEND_Initialize: tensorrt
[component_container-1] I0508 11:27:25.790080 38287 tensorrt.cc:5452] Triton TRITONBACKEND API version: 1.10
[component_container-1] I0508 11:27:25.790082 38287 tensorrt.cc:5458] 'tensorrt' TRITONBACKEND API version: 1.10
[component_container-1] I0508 11:27:25.790083 38287 tensorrt.cc:5486] backend configuration:
[component_container-1] {"cmdline":{"auto-complete-config":"false","min-compute-capability":"6.000000","backend-directory":"/opt/tritonserver/backends","default-max-batch-size":"4"}}
[component_container-1] I0508 11:27:25.790251 38287 tensorrt.cc:5591] TRITONBACKEND_ModelInitialize: peoplesemsegnet_shuffleseg (version 1)
[component_container-1] I0508 11:27:25.790912 38287 tensorrt.cc:5640] TRITONBACKEND_ModelInstanceInitialize: peoplesemsegnet_shuffleseg (GPU device 0)
[component_container-1] I0508 11:27:25.805078 38287 tensorrt.cc:5678] TRITONBACKEND_ModelInstanceFinalize: delete instance state
[component_container-1] I0508 11:27:25.805101 38287 tensorrt.cc:5617] TRITONBACKEND_ModelFinalize: delete model state
[component_container-1] E0508 11:27:25.805110 38287 model_lifecycle.cc:596] failed to load 'peoplesemsegnet_shuffleseg' version 1: Internal: unable to create stream: the provided PTX was compiled with an unsupported toolchain.
[component_container-1] ERROR: infer_trtis_server.cpp:1057 Triton: failed to load model peoplesemsegnet_shuffleseg, triton_err_str:Invalid argument, err_msg:load failed for model 'peoplesemsegnet_shuffleseg': version 1 is at UNAVAILABLE state: Internal: unable to create stream: the provided PTX was compiled with an unsupported toolchain.;
[component_container-1] 
[component_container-1] ERROR: infer_trtis_backend.cpp:54 failed to load model: peoplesemsegnet_shuffleseg, nvinfer error:NVDSINFER_TRITON_ERROR
[component_container-1] ERROR: infer_simple_runtime.cpp:33 failed to initialize backend while ensuring model:peoplesemsegnet_shuffleseg ready, nvinfer error:NVDSINFER_TRITON_ERROR
[component_container-1] ERROR: Error in createNNBackend() <infer_simple_context.cpp:76> [UID = 16]: failed to initialize triton simple runtime for model:peoplesemsegnet_shuffleseg, nvinfer error:NVDSINFER_TRITON_ERROR
[component_container-1] ERROR: Error in initialize() <infer_base_context.cpp:79> [UID = 16]: create nn-backend failed, check config file settings, nvinfer error:NVDSINFER_TRITON_ERROR
[component_container-1] 2023-05-08 19:27:25.805 ERROR /workspaces/isaac_ros-dev/src/isaac_ros_dnn_inference/isaac_ros_triton/gxf/triton/inferencers/triton_inferencer_impl.cpp@326: Failure to initialize Inference Context for 'peoplesemsegnet_shuffleseg'
[component_container-1] 2023-05-08 19:27:25.805 ERROR gxf/std/entity_executor.cpp@541: Entity [SSPKHGPSGC_triton_request] must be in kStarted or kIdle or kTickPending or kTicking stage before stopping. Current state is StartPending
[component_container-1] 2023-05-08 19:27:25.805 ERROR gxf/std/entity_executor.cpp@203: Entity with eid 34 not found!
[component_container-1] [ERROR] [1683545245.805212937] [triton]: [NitrosPublisher] Vault ("vault/vault", eid=34) was stopped. The graph may have been terminated due to an error.
[component_container-1] 2023-05-08 19:27:25.805 WARN  gxf/std/greedy_scheduler.cpp@235: Error while executing entity 16 named 'SSPKHGPSGC_triton_request': GXF_FAILURE
[component_container-1] terminate called after throwing an instance of 'std::runtime_error'
[component_container-1]   what():  [NitrosPublisher] Vault ("vault/vault", eid=34) was stopped. The graph may have been terminated due to an error.
[ERROR] [component_container-1]: process has died [pid 38287, exit code -6, cmd '/opt/ros/humble/install/lib/rclcpp_components/component_container --ros-args -r __node:=triton_container -r __ns:=/triton'].
![image](https://user-images.githubusercontent.com/51771035/236812941-ac910089-2c68-46b8-80b5-02b138c4dd7b.png)

**Comment by hemalshahNV** [comment]
The following line indicates that either you may have recently installed new NVIDIA drivers and need to reboot + reprepare your model (Step 5 of Quickstart) or that you have prepared the model on another machine and copied over the files to run.

```
failed to load 'peoplesemsegnet_shuffleseg' version 1: Internal: unable to create stream: the provided PTX was compiled with an unsupported toolchain
```
