### ISSUE TITLE
ros2 launch isaac_ros_triton demo fails to run

### ISSUE THREAD

**Issue by nxsgis** [NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference#35]
I'm building the NVIDIA-ISAAC ROS dnn interface for the first time and am having a few issues. Running Ubuntu 22.04 and a GTX 745. NVIDIA graphics driver version is 530.41.03. 

I get this error once I run the commands:

> ./scripts/run_dev.sh

Then I source. 

> ros2 launch isaac_ros_triton isaac_ros_triton.launch.py model_name:=peoplesemsegnet_shuffleseg model_repository_paths:=['/tmp/models'] input_binding_names:=['input_2:0'] output_binding_names:=['argmax_1']

I also had a stderr 1 problem with building isaac_ros_triton, but I was able  to run the launch command above and receive this output:

> admin@rosie:/workspaces/isaac_ros-dev$ ros2 launch isaac_ros_triton isaac_ros_triton.launch.py model_name:=peoplesemsegnet_shuffleseg model_repository_paths:=['/tmp/models'] input_binding_names:=['input_2:0'] output_binding_names:=['argmax_1']
[INFO] [launch]: All log files can be found below /home/admin/.ros/log/2023-05-22-11-32-42-146748-rosie-19142
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [component_container-1]: process started with pid [19153]
[component_container-1] [INFO] [1684769563.335663644] [triton.triton_container]: Load Library: /workspaces/isaac_ros-dev/install/isaac_ros_triton/lib/libtriton_node.so
[component_container-1] [INFO] [1684769563.484380874] [triton.triton_container]: Found class: rclcpp_components::NodeFactoryTemplate<nvidia::isaac_ros::dnn_inference::TritonNode>
[component_container-1] [INFO] [1684769563.484490698] [triton.triton_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<nvidia::isaac_ros::dnn_inference::TritonNode>
[component_container-1] [INFO] [1684769563.502691448] [NitrosContext]: [NitrosContext] Creating a new shared context
[component_container-1] [INFO] [1684769563.503017916] [triton]: [NitrosNode] Initializing NitrosNode
[component_container-1] [INFO] [1684769563.506695254] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/std/libgxf_std.so
[component_container-1] [INFO] [1684769563.568062075] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_gxf_helpers.so
[component_container-1] [INFO] [1684769563.644097089] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_sight.so
[component_container-1] [INFO] [1684769563.702077173] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_atlas.so
[component_container-1] [INFO] [1684769563.898933652] [NitrosContext]: [NitrosContext] Loading application: '/workspaces/isaac_ros-dev/install/isaac_ros_nitros/share/isaac_ros_nitros/config/type_adapter_nitros_context_graph.yaml'
[component_container-1] [INFO] [1684769563.927854268] [NitrosContext]: [NitrosContext] Initializing application...
[component_container-1] [INFO] [1684769563.935790905] [NitrosContext]: [NitrosContext] Running application...
[component_container-1] 2023-05-22 11:32:43.935 WARN  gxf/std/program.cpp@456: No system specified. Nothing to do
[component_container-1] [INFO] [1684769563.937480483] [triton]: [NitrosNode] Starting NitrosNode
[component_container-1] [INFO] [1684769563.937518583] [triton]: [NitrosNode] Loading built-in preset extension specs
[component_container-1] [INFO] [1684769563.967474604] [triton]: [NitrosNode] Loading built-in extension specs
[component_container-1] [INFO] [1684769563.967543490] [triton]: [NitrosNode] Loading preset extension specs
[component_container-1] [INFO] [1684769563.969069677] [triton]: [NitrosNode] Loading extension specs
[component_container-1] [INFO] [1684769563.969127887] [triton]: [NitrosNode] Loading generator rules
[component_container-1] [INFO] [1684769563.977597079] [triton]: [NitrosNode] Loading extensions
[component_container-1] [INFO] [1684769563.980307306] [triton]: [NitrosContext] Loading extension: gxf/lib/cuda/libgxf_cuda.so
[component_container-1] [INFO] [1684769564.011143782] [triton]: [NitrosContext] Loading extension: gxf/lib/serialization/libgxf_serialization.so
[component_container-1] [INFO] [1684769564.085232735] [triton]: [NitrosContext] Loading extension: gxf/triton/libgxf_triton_ext.so
[component_container-1] [INFO] [1684769564.619203417] [triton]: [NitrosNode] Loading graph to the optimizer
[component_container-1] [INFO] [1684769564.630495515] [triton]: [NitrosNode] Running optimization
[component_container-1] [INFO] [1684769564.737519976] [triton]: [NitrosNode] Obtaining graph IO group info from the optimizer
[component_container-1] [INFO] [1684769564.746418018] [triton]: [NitrosNode] Creating negotiated publishers/subscribers
[component_container-1] [INFO] [1684769564.746753729] [triton]: [NitrosPublisherSubscriberGroup] Pinning the component "triton_request/input" (type="nvidia::gxf::DoubleBufferReceiver") to use its compatible format only: "nitros_tensor_list_nchw_rgb_f32"
[component_container-1] [INFO] [1684769564.786416919] [triton]: [NitrosPublisherSubscriberGroup] Pinning the component "vault/vault" (type="nvidia::gxf::Vault") to use its compatible format only: "nitros_tensor_list_nhwc_rgb_f32"
[component_container-1] [INFO] [1684769564.787220356] [triton]: [NitrosNode] Starting negotiation...
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/triton' in container '/triton/triton_container'
[component_container-1] [INFO] [1684769565.787677681] [triton]: [NitrosNode] Starting post negotiation setup
[component_container-1] [INFO] [1684769565.787813236] [triton]: [NitrosNode] Getting data format negotiation results
[component_container-1] [INFO] [1684769565.787850076] [triton]: [NitrosSubscriber] Negotiation ended with no results
[component_container-1] [INFO] [1684769565.787874167] [triton]: [NitrosSubscriber] Use the compatible subscriber: topic_name="/tensor_pub", data_format="nitros_tensor_list_nchw_rgb_f32"
[component_container-1] [INFO] [1684769565.787950572] [triton]: [NitrosPublisher] Negotiation ended with no results
[component_container-1] [INFO] [1684769565.787978155] [triton]: [NitrosPublisher] Use only the compatible publisher: topic_name="/tensor_sub", data_format="nitros_tensor_list_nhwc_rgb_f32"
[component_container-1] [INFO] [1684769565.788007983] [triton]: [NitrosNode] Exporting the final graph based on the negotiation results
[component_container-1] [INFO] [1684769565.807820694] [triton]: [NitrosNode] Wrote the final top level YAML graph to "/workspaces/isaac_ros-dev/install/isaac_ros_triton/share/isaac_ros_triton/UVXSRMUCPB.yaml"
[component_container-1] [INFO] [1684769565.807893318] [triton]: [NitrosNode] Calling user's pre-load-graph callback
[component_container-1] [INFO] [1684769565.807901690] [triton]: [NitrosNode] Loading application
[component_container-1] [INFO] [1684769565.807909050] [triton]: [NitrosContext] Loading application: '/workspaces/isaac_ros-dev/install/isaac_ros_triton/share/isaac_ros_triton/UVXSRMUCPB.yaml'
[component_container-1] 2023-05-22 11:32:45.809 WARN  gxf/std/yaml_file_loader.cpp@952: Using unregistered parameter 'dummy_rx' in component 'requester'.
[component_container-1] [INFO] [1684769565.809555864] [triton]: [NitrosNode] Linking Nitros pub/sub to the loaded application
[component_container-1] [INFO] [1684769565.809629808] [triton]: [NitrosNode] Calling user's post-load-graph callback
[component_container-1] [INFO] [1684769565.809642293] [triton]: In TritonNode postLoadGraphCallback().
[component_container-1] [INFO] [1684769565.809684659] [triton]: [NitrosContext] Initializing application...
[component_container-1] WARNING: infer_trtis_server.cpp:1219 NvDsTritonServerInit suggest to set model_control_mode:none. otherwise may cause unknow issues.
[component_container-1] I0522 15:32:46.407227 19153 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x202d80000' with size 268435456
[component_container-1] I0522 15:32:46.414698 19153 cuda_memory_manager.cc:115] CUDA memory pool disabled
[component_container-1] I0522 15:32:46.679047 19153 metrics.cc:864] Collecting metrics for GPU 0: NVIDIA GeForce GTX 745
[component_container-1] I0522 15:32:46.687160 19153 metrics.cc:757] Collecting CPU metrics
[component_container-1] I0522 15:32:46.687425 19153 tritonserver.cc:2264] 
[component_container-1] +----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
[component_container-1] | Option                           | Value                                                                                                                                                                                                |
[component_container-1] +----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
[component_container-1] | server_id                        | triton                                                                                                                                                                                               |
[component_container-1] | server_version                   | 2.26.0                                                                                                                                                                                               |
[component_container-1] | server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics trace logging |
[component_container-1] | model_repository_path[0]         | /tmp/models                                                                                                                                                                                          |
[component_container-1] | model_control_mode               | MODE_EXPLICIT                                                                                                                                                                                        |
[component_container-1] | strict_model_config              | 1                                                                                                                                                                                                    |
[component_container-1] | rate_limit                       | OFF                                                                                                                                                                                                  |
[component_container-1] | pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                                            |
[component_container-1] | response_cache_byte_size         | 0                                                                                                                                                                                                    |
[component_container-1] | min_supported_compute_capability | 6.0                                                                                                                                                                                                  |
[component_container-1] | strict_readiness                 | 1                                                                                                                                                                                                    |
[component_container-1] | exit_timeout                     | 30                                                                                                                                                                                                   |
[component_container-1] +----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
[component_container-1] 
[component_container-1] I0522 15:32:46.696038 19153 server.cc:261] No server context available. Exiting immediately.
[component_container-1] ERROR: infer_trtis_server.cpp:994 Triton: failed to create repo server, triton_err_str:Internal, err_msg:failed to stat file /tmp/models
[component_container-1] ERROR: infer_trtis_server.cpp:840 failed to initialize trtserver on repo dir: root: "/tmp/models"
[component_container-1] log_level: 2
[component_container-1] strict_model_config: true
[component_container-1] tf_disable_soft_placement: true
[component_container-1] min_compute_capacity: 6
[component_container-1] backend_dir: "/opt/tritonserver/backends"
[component_container-1] model_control_mode: "explicit"
[component_container-1] 
[component_container-1] ERROR: infer_trtis_server.cpp:1224 NvDsTritonServerInit failed to get global triton instance
[component_container-1] 2023-05-22 11:32:46.696 ERROR /workspaces/isaac_ros-dev/src/isaac_ros_dnn_inference/isaac_ros_triton/gxf/triton/extensions/triton/triton_server.cpp@91: Error in NvDsTritonServerInit
[component_container-1] 2023-05-22 11:32:46.696 ERROR gxf/std/entity_warden.cpp@380: Failed to initialize component 00015 (server)
[component_container-1] 2023-05-22 11:32:46.696 ERROR gxf/core/runtime.cpp@616: Could not initialize entity 'UVXSRMUCPB_triton_server' (E14): GXF_FAILURE
[component_container-1] 2023-05-22 11:32:46.696 ERROR gxf/std/program.cpp@205: Failed to activate entity 00014 named UVXSRMUCPB_triton_server: GXF_FAILURE
[component_container-1] 2023-05-22 11:32:46.696 ERROR gxf/std/program.cpp@207: Deactivating...
[component_container-1] 2023-05-22 11:32:46.696 ERROR gxf/core/runtime.cpp@1227: Graph activation failed with error: GXF_FAILURE
[component_container-1] [ERROR] [1684769566.696283013] [triton]: [NitrosContext] GxfGraphActivate Error: GXF_FAILURE
[component_container-1] [ERROR] [1684769566.696343066] [triton]: [NitrosNode] runGraphAsync Error: GXF_FAILURE
[component_container-1] terminate called after throwing an instance of 'std::runtime_error'
[component_container-1]   what():  [NitrosNode] runGraphAsync Error: GXF_FAILURE
[ERROR] [component_container-1]: process has died [pid 19153, exit code -6, cmd '/opt/ros/humble/install/lib/rclcpp_components/component_container --ros-args -r __node:=triton_container -r __ns:=/triton'].

Running the colcon build tests outputs this:

> stderr: isaac_ros_image_proc                            
Errors while running CTest
Output from these tests are in: /workspaces/isaac_ros-dev/build/isaac_ros_image_proc/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
> 
> Finished <<< isaac_ros_image_proc [53.7s]       [ with test failures ]
> Starting >>> isaac_ros_stereo_image_proc
> stderr: isaac_ros_stereo_image_proc                            
Errors while running CTest
Output from these tests are in: /workspaces/isaac_ros-dev/build/isaac_ros_stereo_image_proc/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
> 
> Finished <<< isaac_ros_stereo_image_proc [53.9s]        [ with test failures ]
> Starting >>> isaac_ros_tensor_rt
> Finished <<< isaac_ros_tensor_rt [2min 34s]                     
> Starting >>> isaac_ros_triton
> Finished <<< isaac_ros_triton [1min 23s]                     
> Starting >>> isaac_ros_dnn_encoders
> Finished <<< isaac_ros_dnn_encoders [15.3s]                   
> Starting >>> isaac_ros_image_pipeline
> Finished <<< isaac_ros_image_pipeline [0.82s]                  

> Summary: 30 packages finished [8min 20s]
  2 packages had stderr output: isaac_ros_image_proc isaac_ros_stereo_image_proc
  2 packages had test failures: isaac_ros_image_proc isaac_ros_stereo_image_proc

Do you have any idea why this fails?
Thank you very much.

**Comment by jaiveersinghNV** [comment]
Unfortunately, it appears that your GTX 745 card is an older architecture that is not supported with Isaac ROS. As detailed [here](https://github.com/NVIDIA-ISAAC-ROS/.github/blob/main/profile/hardware-setup.md#discrete-gpu), the minimum specification for running Isaac ROS with a Discrete GPU is the Volta architecture and newer.
