### ISSUE TITLE
Compile warning, launch execution failed

### ISSUE THREAD

**Issue by kong9999** [NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference#37]
admin@ubuntu:/workspaces/isaac_ros-dev$ **ros2 launch isaac_ros_triton isaac_ros_triton.launch.py model_name:=peoplesemsegnet_shuffleseg model_repository_paths:=['/tmp/models'] input_binding_names:=['input_2:0'] output_binding_names:=['argmax_1']**
[INFO] [launch]: All log files can be found below /home/admin/.ros/log/2023-06-15-19-27-52-702315-ubuntu-278149
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [component_container-1]: process started with pid [278160]
[component_container-1] [INFO] [1686828473.007430077] [triton.triton_container]: Load Library: /workspaces/isaac_ros-dev/install/isaac_ros_triton/lib/libtriton_node.so
[component_container-1] [INFO] [1686828473.014030018] [triton.triton_container]: Found class: rclcpp_components::NodeFactoryTemplate<nvidia::isaac_ros::dnn_inference::TritonNode>
[component_container-1] [INFO] [1686828473.014056098] [triton.triton_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<nvidia::isaac_ros::dnn_inference::TritonNode>
[component_container-1] [INFO] [1686828473.015374486] [NitrosContext]: [NitrosContext] Creating a new shared context
[component_container-1] [INFO] [1686828473.015421434] [triton]: [NitrosNode] Initializing NitrosNode
[component_container-1] [INFO] [1686828473.015659433] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/std/libgxf_std.so
[component_container-1] [INFO] [1686828473.017262832] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_gxf_helpers.so
[component_container-1] [INFO] [1686828473.018503638] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_sight.so
[component_container-1] [INFO] [1686828473.019666434] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_atlas.so
[component_container-1] [INFO] [1686828473.021583371] [NitrosContext]: [NitrosContext] Loading application: '/workspaces/isaac_ros-dev/install/isaac_ros_nitros/share/isaac_ros_nitros/config/type_adapter_nitros_context_graph.yaml'
[component_container-1] [INFO] [1686828473.021855671] [NitrosContext]: [NitrosContext] Initializing application...
[component_container-1] [INFO] [1686828473.022698073] [NitrosContext]: [NitrosContext] Running application...
[component_container-1] 2023-06-15 19:27:53.022 WARN  gxf/std/program.cpp@456: No system specified. Nothing to do
[component_container-1] [INFO] [1686828473.022911259] [triton]: [NitrosNode] Starting NitrosNode
[component_container-1] [INFO] [1686828473.022917792] [triton]: [NitrosNode] Loading built-in preset extension specs
[component_container-1] [INFO] [1686828473.023918241] [triton]: [NitrosNode] Loading built-in extension specs
[component_container-1] [INFO] [1686828473.023926284] [triton]: [NitrosNode] Loading preset extension specs
[component_container-1] [INFO] [1686828473.024739440] [triton]: [NitrosNode] Loading extension specs
[component_container-1] [INFO] [1686828473.024745947] [triton]: [NitrosNode] Loading generator rules
[component_container-1] [INFO] [1686828473.024841632] [triton]: [NitrosNode] Loading extensions
[component_container-1] [INFO] [1686828473.024903519] [triton]: [NitrosContext] Loading extension: gxf/lib/libgxf_message_compositor.so
[component_container-1] [INFO] [1686828473.025135964] [triton]: [NitrosContext] Loading extension: gxf/lib/cuda/libgxf_cuda.so
[component_container-1] [INFO] [1686828473.026031461] [triton]: [NitrosContext] Loading extension: gxf/lib/serialization/libgxf_serialization.so
[component_container-1] [INFO] [1686828473.027335358] [triton]: [NitrosContext] Loading extension: gxf/triton/libgxf_triton_ext.so
[component_container-1] [INFO] [1686828473.058721706] [triton]: [NitrosNode] Loading graph to the optimizer
[component_container-1] [INFO] [1686828473.059675821] [triton]: [NitrosNode] Running optimization
[component_container-1] [INFO] [1686828473.113501563] [triton]: [NitrosNode] Obtaining graph IO group info from the optimizer
[component_container-1] [INFO] [1686828473.117961615] [triton]: [NitrosNode] Creating negotiated publishers/subscribers
[component_container-1] [INFO] [1686828473.118109880] [triton]: [NitrosPublisherSubscriberGroup] Pinning the component "triton_request/input" (type="nvidia::gxf::DoubleBufferReceiver") to use its compatible format only: "nitros_tensor_list_nchw_rgb_f32"
[component_container-1] [INFO] [1686828473.120015378] [triton]: [NitrosPublisherSubscriberGroup] Pinning the component "sink/sink" (type="nvidia::isaac_ros::MessageRelay") to use its compatible format only: "nitros_tensor_list_nhwc_rgb_f32"
[component_container-1] [INFO] [1686828473.120219941] [triton]: [NitrosNode] Starting negotiation...
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/triton' in container '/triton/triton_container'
[component_container-1] [INFO] [1686828474.120561423] [triton]: [NitrosNode] Starting post negotiation setup
[component_container-1] [INFO] [1686828474.120693233] [triton]: [NitrosNode] Getting data format negotiation results
[component_container-1] [INFO] [1686828474.120721110] [triton]: [NitrosSubscriber] Negotiation ended with no results
[component_container-1] [INFO] [1686828474.120738940] [triton]: [NitrosSubscriber] Use the compatible subscriber: topic_name="/tensor_pub", data_format="nitros_tensor_list_nchw_rgb_f32"
[component_container-1] [INFO] [1686828474.120816673] [triton]: [NitrosPublisher] Negotiation ended with no results
[component_container-1] [INFO] [1686828474.120833262] [triton]: [NitrosPublisher] Use only the compatible publisher: topic_name="/tensor_sub", data_format="nitros_tensor_list_nhwc_rgb_f32"
[component_container-1] [INFO] [1686828474.120858565] [triton]: [NitrosNode] Exporting the final graph based on the negotiation results
[component_container-1] [INFO] [1686828474.131647631] [triton]: [NitrosNode] Wrote the final top level YAML graph to "/workspaces/isaac_ros-dev/install/isaac_ros_triton/share/isaac_ros_triton/ORKVHIVHRA.yaml"
[component_container-1] [INFO] [1686828474.131661076] [triton]: [NitrosNode] Calling user's pre-load-graph callback
[component_container-1] [INFO] [1686828474.131679835] [triton]: [NitrosNode] Loading application
[component_container-1] [INFO] [1686828474.131684232] [triton]: [NitrosContext] Loading application: '/workspaces/isaac_ros-dev/install/isaac_ros_triton/share/isaac_ros_triton/ORKVHIVHRA.yaml'
[component_container-1] 2023-06-15 19:27:54.132 WARN  gxf/std/yaml_file_loader.cpp@952: Using unregistered parameter 'dummy_rx' in component 'requester'.
[component_container-1] [INFO] [1686828474.132451121] [triton]: [NitrosNode] Linking Nitros pub/sub to the loaded application
[component_container-1] [INFO] [1686828474.132491800] [triton]: [NitrosNode] Calling user's post-load-graph callback
[component_container-1] [INFO] [1686828474.132496913] [triton]: In TritonNode postLoadGraphCallback().
[component_container-1] [INFO] [1686828474.132522546] [triton]: [NitrosContext] Initializing application...
[component_container-1] WARNING: infer_trtis_server.cpp:1219 NvDsTritonServerInit suggest to set model_control_mode:none. otherwise may cause unknow issues.
[component_container-1] I0615 11:27:54.229629 278160 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7f568c000000' with size 268435456
[component_container-1] I0615 11:27:54.229740 278160 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
[component_container-1] I0615 11:27:54.230304 278160 server.cc:563]
[component_container-1] +------------------+------+
[component_container-1] | Repository Agent | Path |
[component_container-1] +------------------+------+
[component_container-1] +------------------+------+
[component_container-1]
[component_container-1] I0615 11:27:54.230313 278160 server.cc:590]
[component_container-1] +---------+------+--------+
[component_container-1] | Backend | Path | Config |
[component_container-1] +---------+------+--------+
[component_container-1] +---------+------+--------+
[component_container-1]
[component_container-1] I0615 11:27:54.230317 278160 server.cc:633]
[component_container-1] +-------+---------+--------+
[component_container-1] | Model | Version | Status |
[component_container-1] +-------+---------+--------+
[component_container-1] +-------+---------+--------+
[component_container-1]
[component_container-1] I0615 11:27:54.250527 278160 metrics.cc:864] Collecting metrics for GPU 0: NVIDIA GeForce RTX 3080
[component_container-1] I0615 11:27:54.250740 278160 metrics.cc:757] Collecting CPU metrics
[component_container-1] I0615 11:27:54.250822 278160 tritonserver.cc:2264]
[component_container-1] +----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
[component_container-1] | Option                           | Value                                                                                                                                                                                                |
[component_container-1] +----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
[component_container-1] | server_id                        | triton                                                                                                                                                                                               |
[component_container-1] | server_version                   | 2.26.0                                                                                                                                                                                               |
[component_container-1] | server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics trace logging |
[component_container-1] | model_repository_path[0]         | /tmp/models                                                                                                                                                                                          |
[component_container-1] | model_control_mode               | MODE_EXPLICIT                                                                                                                                                                                        |
[component_container-1] | strict_model_config              | 1                                                                                                                                                                                                    |
[component_container-1] | rate_limit                       | OFF                                                                                                                                                                                                  |
[component_container-1] | pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                                            |
[component_container-1] | cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                                                                             |
[component_container-1] | response_cache_byte_size         | 0                                                                                                                                                                                                    |
[component_container-1] | min_supported_compute_capability | 6.0                                                                                                                                                                                                  |
[component_container-1] | strict_readiness                 | 1                                                                                                                                                                                                    |
[component_container-1] | exit_timeout                     | 30                                                                                                                                                                                                   |
[component_container-1] +----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
[component_container-1]
[component_container-1] [INFO] [1686828474.251106529] [triton]: [NitrosContext] Running application...
[component_container-1] [INFO] [1686828474.251163596] [triton]: [NitrosNode] Starting a heartbeat timer (eid=16)
[component_container-1] I0615 11:27:54.252079 278160 model_lifecycle.cc:459] loading: peoplesemsegnet_shuffleseg:1
[component_container-1] I0615 11:27:54.273771 278160 tensorrt.cc:5442] TRITONBACKEND_Initialize: tensorrt
[component_container-1] I0615 11:27:54.273783 278160 tensorrt.cc:5452] Triton TRITONBACKEND API version: 1.10
[component_container-1] I0615 11:27:54.273787 278160 tensorrt.cc:5458] 'tensorrt' TRITONBACKEND API version: 1.10
[component_container-1] I0615 11:27:54.273789 278160 tensorrt.cc:5486] backend configuration:
[component_container-1] {"cmdline":{"auto-complete-config":"false","min-compute-capability":"6.000000","backend-directory":"/opt/tritonserver/backends","default-max-batch-size":"4"}}
[component_container-1] I0615 11:27:54.273969 278160 tensorrt.cc:5591] TRITONBACKEND_ModelInitialize: peoplesemsegnet_shuffleseg (version 1)
[component_container-1] I0615 11:27:54.274626 278160 tensorrt.cc:5640] TRITONBACKEND_ModelInstanceInitialize: peoplesemsegnet_shuffleseg (GPU device 0)
[component_container-1] I0615 11:27:54.288726 278160 tensorrt.cc:5678] TRITONBACKEND_ModelInstanceFinalize: delete instance state
[component_container-1] I0615 11:27:54.288740 278160 tensorrt.cc:5617] TRITONBACKEND_ModelFinalize: delete model state
[component_container-1] E0615 11:27:54.288747 278160 model_lifecycle.cc:596] failed to load 'peoplesemsegnet_shuffleseg' version 1: Internal: unable to create stream: the provided PTX was compiled with an unsupported toolchain.
[component_container-1] ERROR: infer_trtis_server.cpp:1057 Triton: failed to load model peoplesemsegnet_shuffleseg, triton_err_str:Invalid argument, err_msg:load failed for model 'peoplesemsegnet_shuffleseg': version 1 is at UNAVAILABLE state: Internal: unable to create stream: the provided PTX was compiled with an unsupported toolchain.;
[component_container-1]
[component_container-1] ERROR: infer_trtis_backend.cpp:54 failed to load model: peoplesemsegnet_shuffleseg, nvinfer error:NVDSINFER_TRITON_ERROR
[component_container-1] ERROR: infer_simple_runtime.cpp:33 failed to initialize backend while ensuring model:peoplesemsegnet_shuffleseg ready, nvinfer error:NVDSINFER_TRITON_ERROR
[component_container-1] ERROR: Error in createNNBackend() <infer_simple_context.cpp:76> [UID = 16]: failed to initialize triton simple runtime for model:peoplesemsegnet_shuffleseg, nvinfer error:NVDSINFER_TRITON_ERROR
[component_container-1] ERROR: Error in initialize() <infer_base_context.cpp:79> [UID = 16]: create nn-backend failed, check config file settings, nvinfer error:NVDSINFER_TRITON_ERROR
[component_container-1] 2023-06-15 19:27:54.288 ERROR /workspaces/isaac_ros-dev/src/isaac_ros_dnn_inference/isaac_ros_triton/gxf/triton/inferencers/triton_inferencer_impl.cpp@326: Failure to initialize Inference Context for 'peoplesemsegnet_shuffleseg'
[component_container-1] 2023-06-15 19:27:54.288 ERROR gxf/std/entity_executor.cpp@540: Entity [ORKVHIVHRA_triton_request] must be in Lifecycle::kStarted or Lifecycle::kIdle stage before stopping. Current state is StartPending
[component_container-1] 2023-06-15 19:27:54.288 WARN  gxf/std/greedy_scheduler.cpp@241: Error while executing entity 16 named 'ORKVHIVHRA_triton_request': GXF_FAILURE
[component_container-1] 2023-06-15 19:27:55.251 ERROR gxf/std/entity_executor.cpp@203: Entity with eid 16 not found!
[component_container-1] [WARN] [1686828475.251504660] [triton]: [NitrosNode] The heartbeat entity (eid=16) was stopped. The graph may have been terminated.
[component_container-1] [INFO] [1686828475.255870227] [triton]: [NitrosNode] Terminating the running application
[component_container-1] [INFO] [1686828475.255909899] [triton]: [NitrosContext] Interrupting GXF...
[component_container-1] [INFO] [1686828475.255938944] [triton]: [NitrosContext] Waiting on GXF...
[component_container-1] 2023-06-15 19:27:55.255 ERROR gxf/std/program.cpp@497: wait failed. Deactivating...
[component_container-1] 2023-06-15 19:27:55.256 ERROR gxf/core/runtime.cpp@1251: Graph wait failed with error: GXF_FAILURE
[component_container-1] [ERROR] [1686828475.256345548] [triton]: [NitrosContext] GxfGraphWait Error: GXF_FAILURE
[component_container-1] [INFO] [1686828475.256352619] [triton]: [NitrosNode] Application termination done
[INFO] [component_container-1]: process has finished cleanly [pid 278160]
![image](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference/assets/51771035/32352ec3-25ec-48c5-9f4d-a92af96c0774)

 **When I execute colcon build --symlink-install,I am faced with the following problems.**
![image](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference/assets/51771035/79bf635d-2070-4e6c-94c3-c677ebce96c9)

**The launch does not work. Is it related to this? My network here is not very good, when compiling will encounter warnings.I look forward to your reply. Thank you**

**Comment by swapnesh-wani-nvidia** [comment]
It looks like from this error msg "the provided PTX was compiled with an unsupported toolchain" that your driver might be old. Could you please provide the driver details and GPU that you used?

**Comment by kong9999** [comment]
> It looks like from this error msg "the provided PTX was compiled with an unsupported toolchain" that your driver might be old. Could you please provide the driver details and GPU that you used?

![image](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference/assets/51771035/786b1479-0073-4860-8141-2bed0fe64423)

**Comment by swapnesh-wani-nvidia** [comment]
Could  you provide the output of 
`nvidia-smi -q`
