### ISSUE TITLE
ros2 topic list does not show /tensor_pub, /tensor_sub, etc.

### ISSUE THREAD

**Issue by EricleiKUANG** [NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference#5]
Hi,
I tried the ros2 topic list but can not see topics like tensor_pub, tensor_sub, or image_publisher.
Even I tried running with `export ROS_DOMAIN_ID=1`, I can not see the topics.
Btw in initial release I can see the topics, but with the latest commit I cann't.
Any advice?

**Comment by hemalshahNV** [comment]
We have not been able to reproduce locally. Could you tell us a bit about your setup? What model are you loading, what package are you using (TensorRT or Triton), what platform you are on, etc.?

**Comment by Doch88** [comment]
This should be fixed by this:
[https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/pull/24](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/pull/24)

**Comment by hemalshahNV** [comment]
We'll include @Doch88 fix in the next release of Isaac ROS shortly. Did this happen to resolve your issue though?

**Comment by hemalshahNV** [comment]
We included @Doch88 's fix in Isaac ROS DP1.1 (v0.11.0). Let us know if this remains an issue. Thanks!
